---
# Ansible Galaxy requirements file
# Install with: ansible-galaxy install -r requirements.yml

collections:
  - name: community.general
    version: ">=12.0.0"
  - name: ansible.posix
    version: ">=1.5.0"

roles:
  - name: geerlingguy.docker
    version: "7.4.0"
